apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
        ports:
        - containerPort: 5432
